[workspace]
resolver = "3"
members = [
    "crates/minnow-app",
]
default-members = ["crates/minnow-app"]

[workspace.dependencies]
ab_glyph = "0.2.32"
anyhow = "1.0"
arboard = "3.6"
auto-launch = "0.6"
ctrlc = "3.5"
dhat = "0.3"
directories = "6.0"
font-kit = "0.14"
futures-util = "0.3"
global-hotkey = { version = "0.8", features = ["tracing"] }
gpui = { version = "0.2.2", features = ["runtime_shaders"] }
gpui-component = "0.5.1"
gpui-component-assets = "0.5.1"
ico = "0.5"
image = { version = "0.25", default-features = false }
imageproc = { version = "0.27", default-features = false, features = ["text"] }
mimalloc = "0.1"
ndarray = "0.17"
notify-rust = "4"
num-traits = "0.2"
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["NSApplication", "NSScreen", "NSView", "NSWindow"] }
ort = "=2.0.0-rc.13"
oxipng = { version = "10.2", default-features = false, features = ["parallel"] }
raw-window-handle = "0.6"
rayon = "1.8"
reqwest = { version = "0.13.2", default-features = false, features = ["rustls", "stream"] }
rodio = { version = "0.22.2", default-features = false, features = ["playback", "mp3"] }
rqrr = "0.10"
rust-embed = "8"
rust-i18n = "3.1.5"
serde = { version = "1.0", features = ["derive"] }
single-instance = "0.3"
sys-locale = "0.3.2"
tauri-winrt-notification = "0.8.1"
thiserror = "2.0"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "fs", "io-util", "time", "net"] }
tokio-util = "0.7"
toml = "1.0"
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["ansi", "env-filter", "smallvec", "tracing-log"] }
tray-icon = "0.24"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
winreg = "0.56"
winres = "0.1"
xcap = { version = "0.9", default-features = false }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
